apiVersion: v1
kind: Service
metadata:
  labels:
    run: vote-deployments
  name: vote-service
spec:
  ports:
  - name: 5000-80
    nodePort: 31000
    port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    run: vote-deployment
  type: NodePort
