apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: vote-deployment
  name: vote-deployment
spec:
  containers:
  - image: kodekloud/examplevotingapp_vote:before
    name: vote-deployment
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
