apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: vote-deployment
  name: vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: vote-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: vote-deployment
    spec:
      containers:
      - image: kodekloud/examplevotingapp_vote:before
        name: vote-deployment
        resources: {}
status: {}
