apiVersion: v1
kind: Service
metadata:
  labels:
    run: redis-deployment
  name: redis
spec:
  ports:
  - name: 6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: redis-deployment
  type: ClusterIP
