apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: vote
  labels:
    run: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis-deployment
  template:
    metadata:
      labels:
        run: redis-deployment
    spec:
      containers:
      - image: redis:alpine
        name: redis-deployment
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
        - name: redis-data
          emptyDir:
