apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote
  labels:
    run: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      run: worker
  template:
    metadata:
      labels:
        run: worker
    spec:
      containers:
      - image: kodekloud/examplevotingapp_worker
        name: worker
