apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: vote
  labels:
    run: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: db-deployment
  template:
    metadata:
      labels:
        run: db-deployment
    spec:
      containers:
      - image: postgres:9.4
        name: db-deployment
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_PASSWORD
          value: password
      volumes:
        - name: db-data
          emptyDir:
status: {}
