apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: worker
  name: worker
spec:
  containers:
  - image: postgres:9.4
    name: worker
    resources: {}
  volumes:
  - mountPath: /var/lib/postgresql/data
    name: db-data
  volumes:
  - name: db-data
    emptyDir: 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
