apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote
  labels:
    run: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: result-deployment
  template:
    metadata:
      labels:
        run: result-deployment
    spec:
      containers:
      - image: kodekloud/examplevotingapp_result:before
        name: result-deployment
