apiVersion: v1
kind: Service
metadata:
  labels:
    run: result-deployments
  name: result
spec:
  ports:
  - name: 5001-80
    nodePort: 31001
    port: 5001
    protocol: TCP
    targetPort: 80
  selector:
    run: result-deployment
  type: NodePort
status:
  loadBalancer: {}
