apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: iron-db-service
  name: iron-db-service
spec:
  ports:
  - name: "3600"
    port: 3600
    protocol: TCP
    targetPort: 3600
  selector:
    app: iron-db-service
  type: ClusterIP
status:
  loadBalancer: {}
